import { Injectable } from '@angular/core';
import {PElement}from "./pelement";

@Injectable({
  providedIn: 'root'
})
export class ElementsService {

  constructor() { }

  elements:PElement[]=[
    { xPos:0,yPos:0,name:"Hydrogen", atomicNumber:1, mass:1.008, category: "Reactivenonmetal", symbol:"H" },
    { xPos:17,yPos:0,name:"Helium", atomicNumber:2, mass:1.008, category: "Noblegas", symbol:"He" },
    { xPos:0,yPos:1,name:"Lithium", atomicNumber:3, mass:1.008, category: "Alkalimetal ", symbol:"Li" },
    { xPos:1,yPos:1,name:"Beryllium", atomicNumber:4, mass:1.008, category: "Alkalineearthmetal", symbol:"Be" },
    { xPos:12,yPos:1,name:"Boron", atomicNumber:5, mass:1.008, category: "Metalloid", symbol:"B" },
    { xPos:13,yPos:1,name:"Carbon", atomicNumber:6, mass:1.008, category: "Reactivenonmetal", symbol:"C" },
    { xPos:14,yPos:1,name:"Nitrogen", atomicNumber:7, mass:1.008, category: "Reactivenonmetal", symbol:"N" },
    { xPos:15,yPos:1,name:"Oxygen", atomicNumber:8, mass:1.008, category: "Reactivenonmetal", symbol:"O" },
    { xPos:16,yPos:1,name:"Fluorine", atomicNumber:9, mass:1.008, category: "Reactivenonmetal", symbol:"F" },
    { xPos:17,yPos:1,name:"Neon", atomicNumber:10, mass:1.008, category: "Noblegas", symbol:"Ne" },

    { xPos:0,yPos:2,name:"Sodium", atomicNumber:11, mass:1.008, category: "Alkalimetal", symbol:"Na" },
    { xPos:1,yPos:2,name:"Magnesium", atomicNumber:12, mass:1.008, category: "Alkalineearthmetal", symbol:"Mg" },
    { xPos:12,yPos:2,name:"Aluminium", atomicNumber:13, mass:1.008, category: "Post-transitionmetals", symbol:"Al" },
    { xPos:13,yPos:2,name:"Silicon", atomicNumber:14, mass:1.008, category: "Metalloid", symbol:"Si" },
    { xPos:14,yPos:2,name:"Phosphorus", atomicNumber:15, mass:1.008, category: "Reactivenonmetal", symbol:"P" },
    { xPos:15,yPos:2,name:"Sulfur", atomicNumber:16, mass:1.008, category: "Reactivenonmetal", symbol:"S" },
    { xPos:16,yPos:2,name:"Chlorine", atomicNumber:17, mass:1.008, category: "Reactivenonmetal", symbol:"Cl" },
    { xPos:17,yPos:2,name:"Argon", atomicNumber:18, mass:1.008, category: "Noblegas", symbol:"Ar" },

    { xPos:0,yPos:3,name:"Potassium", atomicNumber:19, mass:1.008, category: "Alkalimetal", symbol:"K" },
    { xPos:1,yPos:3,name:"Calcium", atomicNumber:20, mass:1.008, category: "Alkalineearthmetal", symbol:"Ca" },
    { xPos:2,yPos:3,name:"Scandium", atomicNumber:21, mass:1.008, category: "Transitionmetal", symbol:"Sc" },
    { xPos:3,yPos:3,name:"Titanium", atomicNumber:22, mass:1.008, category: "Transitionmetal", symbol:"Ti" },
    { xPos:4,yPos:3,name:"Vanadium", atomicNumber:23, mass:1.008, category: "Transitionmetal", symbol:"V" },
    { xPos:5,yPos:3,name:"Chromium", atomicNumber:24, mass:1.008, category: "Transitionmetal", symbol:"Cr" },
    { xPos:6,yPos:3,name:"Manganese", atomicNumber:25, mass:1.008, category: "Transitionmetal", symbol:"Mn" },
    { xPos:7,yPos:3,name:"Iron", atomicNumber:26, mass:1.008, category: "Transitionmetal", symbol:"Fe" },
    { xPos:8,yPos:3,name:"Cobalt", atomicNumber:27, mass:1.008, category: "Transitionmetal", symbol:"Co" },
    { xPos:9,yPos:3,name:"Nickel", atomicNumber:28, mass:1.008, category: "Transitionmetal", symbol:"Ni" },
    { xPos:10,yPos:3,name:"Copper", atomicNumber:29, mass:1.008, category: "Transitionmetal", symbol:"Cu" },
    { xPos:11,yPos:3,name:"Zinc", atomicNumber:30, mass:1.008, category: "Transitionmetal", symbol:"Zn" },
    { xPos:12,yPos:3,name:"Gallium", atomicNumber:31, mass:1.008, category: "Post-transitionmetals", symbol:"Ga" },
    { xPos:13,yPos:3,name:"Germanium", atomicNumber:32, mass:1.008, category: "Metalloid", symbol:"Ge" },
    { xPos:14,yPos:3,name:"Arsenic", atomicNumber:33, mass:1.008, category: "Metalloid", symbol:"As" },
    { xPos:15,yPos:3,name:"Selenium", atomicNumber:34, mass:1.008, category: "Reactivenonmetal", symbol:"Se" },
    { xPos:16,yPos:3,name:"Bromine", atomicNumber:35, mass:1.008, category: "Reactivenonmetal", symbol:"Br" },
    { xPos:17,yPos:3,name:"Krypton", atomicNumber:36, mass:1.008, category: "Noblegas", symbol:"Kr" },

    { xPos:0,yPos:4,name:"Rubidium", atomicNumber:37, mass:1.008, category: "Alkalimetal", symbol:"Rb" },
    { xPos:1,yPos:4,name:"Strontium", atomicNumber:38, mass:1.008, category: "Alkalineearthmetal", symbol:"Sr" },
    { xPos:2,yPos:4,name:"Yttrium", atomicNumber:39, mass:1.008, category: "Transitionmetal", symbol:"Y" },
    { xPos:3,yPos:4,name:"Zirconium", atomicNumber:40, mass:1.008, category: "Transitionmetal", symbol:"Zr" },
    { xPos:4,yPos:4,name:"Niobium", atomicNumber:41, mass:1.008, category: "Transitionmetal", symbol:"Nb" },
    { xPos:5,yPos:4,name:"Molybdenum", atomicNumber:42, mass:1.008, category: "Transitionmetal", symbol:"Mo" },
    { xPos:6,yPos:4,name:"Technetium", atomicNumber:43, mass:1.008, category: "Transitionmetal", symbol:"Tc" },
    { xPos:7,yPos:4,name:"Ruthenium", atomicNumber:44, mass:1.008, category: "Transitionmetal", symbol:"Ru" },
    { xPos:8,yPos:4,name:"Rhodium", atomicNumber:45, mass:1.008, category: "Transitionmetal", symbol:"Rh" },
    { xPos:9,yPos:4,name:"Palladium", atomicNumber:46, mass:1.008, category: "Transitionmetal", symbol:"Pd" },
    { xPos:10,yPos:4,name:"Silver", atomicNumber:47, mass:1.008, category: "Transitionmetal", symbol:"Ag" },
    { xPos:11,yPos:4,name:"Cadmium", atomicNumber:48, mass:1.008, category: "Transitionmetal", symbol:"Cd" },
    { xPos:12,yPos:4,name:"Indium", atomicNumber:49, mass:1.008, category: "Post-transitionmetals", symbol:"In" },
    { xPos:13,yPos:4,name:"Tin", atomicNumber:50, mass:1.008, category: "Post-transitionmetals", symbol:"Sn" },
    { xPos:14,yPos:4,name:"Antimony", atomicNumber:51, mass:1.008, category: "Metalloid", symbol:"Sb" },
    { xPos:15,yPos:4,name:"Tellurium", atomicNumber:52, mass:1.008, category: "Metalloid", symbol:"Te" },
    { xPos:16,yPos:4,name:"Iodine", atomicNumber:53, mass:1.008, category: "Reactivenonmetal", symbol:"I" },
    { xPos:17,yPos:4,name:"Xenon", atomicNumber:54, mass:1.008, category: "Noblegas", symbol:"Xe" },

    { xPos:0,yPos:5,name:"Caesium", atomicNumber:55, mass:1.008, category: "Alkalimetal", symbol:"Cs" },
    { xPos:1,yPos:5,name:"Barium", atomicNumber:56, mass:1.008, category: "Alkalineearthmetal", symbol:"Ba" },
    
    { xPos:3,yPos:5,name:"Hafnium", atomicNumber:72, mass:1.008, category: "Transitionmetal", symbol:"Hf" },
    { xPos:4,yPos:5,name:"Tantalum", atomicNumber:73, mass:1.008, category: "Transitionmetal", symbol:"Ta" },
    { xPos:5,yPos:5,name:"Tungsten", atomicNumber:74, mass:1.008, category: "Transitionmetal", symbol:"W" },
    { xPos:6,yPos:5,name:"Rhenium", atomicNumber:75, mass:1.008, category: "Transitionmetal", symbol:"Re" },
    { xPos:7,yPos:5,name:"Osmium", atomicNumber:76, mass:1.008, category: "Transitionmetal", symbol:"Os" },
    { xPos:8,yPos:5,name:"Iridium", atomicNumber:77, mass:1.008, category: "Transitionmetal", symbol:"Ir" },
    { xPos:9,yPos:5,name:"Platinum", atomicNumber:78, mass:1.008, category: "Transitionmetal", symbol:"Pt" },
    { xPos:10,yPos:5,name:"Gold", atomicNumber:79, mass:1.008, category: "Transitionmetal", symbol:"Au" },
    { xPos:11,yPos:5,name:"Mercury", atomicNumber:80, mass:1.008, category: "Transitionmetal", symbol:"Hg" },
    { xPos:12,yPos:5,name:"Thallium", atomicNumber:81, mass:1.008, category: "Post-transitionmetals", symbol:"Tl" },
    { xPos:13,yPos:5,name:"Lead", atomicNumber:82, mass:1.008, category: "Post-transitionmetals", symbol:"Pb" },
    { xPos:14,yPos:5,name:"Bismuth", atomicNumber:83, mass:1.008, category: "Post-transitionmetals", symbol:"Bi" },
    { xPos:15,yPos:5,name:"Polonium", atomicNumber:84, mass:1.008, category: "Post-transitionmetals", symbol:"Po" },
    { xPos:16,yPos:5,name:"Astatine", atomicNumber:85, mass:1.008, category: "Metalloid", symbol:"At" },
    { xPos:17,yPos:5,name:"Radon", atomicNumber:86, mass:1.008, category: "Noblegas", symbol:"Rn" },
    
    { xPos:0,yPos:6,name:"Francium", atomicNumber:87, mass:1.008, category: "Alkalimetal", symbol:"Fr" },
    { xPos:1,yPos:6,name:"Radium", atomicNumber:88, mass:1.008, category: "Alkalineearthmetal", symbol:"Ra" },
    
    { xPos:3,yPos:6,name:"Rutherfordium", atomicNumber:104, mass:1.008, category: "Transitionmetal", symbol:"Rf" },
    { xPos:4,yPos:6,name:"Dubnium", atomicNumber:105, mass:1.008, category: "Transitionmetal", symbol:"Db" },
    { xPos:5,yPos:6,name:"Seaborgium", atomicNumber:106, mass:1.008, category: "Transitionmetal", symbol:"Sg" },
    { xPos:6,yPos:6,name:"Bohrium", atomicNumber:107, mass:1.008, category: "Transitionmetal", symbol:"Bh" },
    { xPos:7,yPos:6,name:"Hassium", atomicNumber:108, mass:1.008, category: "Transitionmetal", symbol:"Hs" },
    { xPos:8,yPos:6,name:"Meitnerium", atomicNumber:109, mass:1.008, category: "", symbol:"Mt" },
    { xPos:9,yPos:6,name:"Darmstadtium", atomicNumber:110, mass:1.008, category: "", symbol:"Ds" },
    { xPos:10,yPos:6,name:"Roentgenium", atomicNumber:111, mass:1.008, category: "", symbol:"Rg" },
    { xPos:11,yPos:6,name:"Copernicium", atomicNumber:112, mass:1.008, category: "", symbol:"Cn" },
    { xPos:12,yPos:6,name:"Nihonium", atomicNumber:113, mass:1.008, category: "", symbol:"Nh" },
    { xPos:13,yPos:6,name:"Flerovium", atomicNumber:114, mass:1.008, category: "", symbol:"Fl" },
    { xPos:14,yPos:6,name:"Moscovium", atomicNumber:115, mass:1.008, category: "", symbol:"Mc" },
    { xPos:15,yPos:6,name:"Livermorium", atomicNumber:116, mass:1.008, category: "", symbol:"Lv" },
    { xPos:16,yPos:6,name:"Tennessine", atomicNumber:117, mass:1.008, category: "", symbol:"Ts" },
    { xPos:17,yPos:6,name:"Oganesson", atomicNumber:118, mass:1.008, category: "", symbol:"Og" },

    { xPos:3,yPos:8,name:"Lanthanum", atomicNumber:57, mass:1.008, category: "Lanthanoid", symbol:"La" },
    { xPos:4,yPos:8,name:"Cerium", atomicNumber:58, mass:1.008, category: "Lanthanoid", symbol:"Ce" },
    { xPos:5,yPos:8,name:"Praseodymium", atomicNumber:59, mass:1.008, category: "Lanthanoid", symbol:"Pr" },
    { xPos:6,yPos:8,name:"Neodymium", atomicNumber:60, mass:1.008, category: "Lanthanoid", symbol:"Nd" },
    { xPos:7,yPos:8,name:"Promethium", atomicNumber:61, mass:1.008, category: "Lanthanoid", symbol:"Pm" },
    { xPos:8,yPos:8,name:"Samarium", atomicNumber:62, mass:1.008, category: "Lanthanoid", symbol:"Sm" },
    { xPos:9,yPos:8,name:"Europium", atomicNumber:63, mass:1.008, category: "Lanthanoid", symbol:"Eu" },
    { xPos:10,yPos:8,name:"Gadolinium", atomicNumber:64, mass:1.008, category: "Lanthanoid", symbol:"Gd" },
    { xPos:11,yPos:8,name:"Terbium", atomicNumber:65, mass:1.008, category: "Lanthanoid", symbol:"Tb" },
    { xPos:12,yPos:8,name:"Dysprosium", atomicNumber:66, mass:1.008, category: "Lanthanoid", symbol:"Dy" },
    { xPos:13,yPos:8,name:"Holmium", atomicNumber:67, mass:1.008, category: "Lanthanoid", symbol:"Ho" },
    { xPos:14,yPos:8,name:"Erbium", atomicNumber:68, mass:1.008, category: "Lanthanoid", symbol:"Er" },
    { xPos:15,yPos:8,name:"Thulium", atomicNumber:69, mass:1.008, category: "Lanthanoid", symbol:"Tm" },
    { xPos:16,yPos:8,name:"Ytterbium", atomicNumber:70, mass:1.008, category: "Lanthanoid", symbol:"Yb" },
    { xPos:17,yPos:8,name:"Lutetium", atomicNumber:71, mass:1.008, category: "Lanthanoid", symbol:"Lu" },

    { xPos:3,yPos:9,name:"Actinium", atomicNumber:89, mass:1.008, category: "Actinide", symbol:"Ac" },
    { xPos:4,yPos:9,name:"Thorium", atomicNumber:90, mass:1.008, category: "Actinide", symbol:"Th" },
    { xPos:5,yPos:9,name:"Protactinium", atomicNumber:91, mass:1.008, category: "Actinide", symbol:"Pa" },
    { xPos:6,yPos:9,name:"Uranium", atomicNumber:92, mass:1.008, category: "Actinide", symbol:"U" },
    { xPos:7,yPos:9,name:"Neptunium", atomicNumber:93, mass:1.008, category: "Actinide", symbol:"Np" },
    { xPos:8,yPos:9,name:"Plutonium", atomicNumber:94, mass:1.008, category: "Actinide", symbol:"Pu" },
    { xPos:9,yPos:9,name:"Americium", atomicNumber:95, mass:1.008, category: "Actinide", symbol:"Am" },
    { xPos:10,yPos:9,name:"Curium", atomicNumber:96, mass:1.008, category: "Actinide", symbol:"Cm" },
    { xPos:11,yPos:9,name:"Berkelium", atomicNumber:97, mass:1.008, category: "Actinide", symbol:"Bk" },
    { xPos:12,yPos:9,name:"Californium", atomicNumber:98, mass:1.008, category: "Actinide", symbol:"Cf" },
    { xPos:13,yPos:9,name:"Einsteinium", atomicNumber:99, mass:1.008, category: "Actinide", symbol:"Es" },
    { xPos:14,yPos:9,name:"Fermium", atomicNumber:100, mass:1.008, category: "Actinide", symbol:"Fm" },
    { xPos:15,yPos:9,name:"Mendelevium", atomicNumber:101, mass:1.008, category: "Actinide", symbol:"Md" },
    { xPos:16,yPos:9,name:"Nobelium", atomicNumber:102, mass:1.008, category: "Actinide", symbol:"No" },
    { xPos:17,yPos:9,name:"Lawrencium", atomicNumber:103, mass:1.008, category: "Actinide", symbol:"Lr" },




  ]

}
